CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    balance INT NOT NULL
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    order_id INT NOT NULL REFERENCES Order(id),
    fulfillment_status VARCHAR(255) NOT NULL 
);

CREATE TABLE Products (
    pid INT NOT NULL PRIMARY KEY,
    short_name VARCHAR(255),
    category VARCHAR(255),
    longer_description VARCHAR(255) NOT NULL,
    product_image, 
    price,
    details,
    list_of_sellers,

);

CREATE TABLE Cart (
    
);

CREATE TABLE Order (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    time_order timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    total_amount FLOAT NOT NULL,
    number_items INT NOT NULL

    
);

CREATE TABLE Inventory (
    
);

CREATE TABLE Review (
    
);



